# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClearMapGui(object):
    def setupUi(self, ClearMapGui):
        ClearMapGui.setObjectName("ClearMapGui")
        ClearMapGui.resize(1950, 1150)
        ClearMapGui.setMinimumSize(QtCore.QSize(1600, 1000))
        ClearMapGui.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.centralwidget = QtWidgets.QWidget(ClearMapGui)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(50, 30))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo_cyber.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(400, 780))
        self.tabWidget.setMaximumSize(QtCore.QSize(400, 780))
        self.tabWidget.setObjectName("tabWidget")
        self.sample_tab = QtWidgets.QWidget()
        self.sample_tab.setObjectName("sample_tab")
        self.tabWidget.addTab(self.sample_tab, "")
        self.preprocessing_tab = QtWidgets.QWidget()
        self.preprocessing_tab.setObjectName("preprocessing_tab")
        self.tabWidget.addTab(self.preprocessing_tab, "")
        self.cell_map_tab = QtWidgets.QWidget()
        self.cell_map_tab.setObjectName("cell_map_tab")
        self.tabWidget.addTab(self.cell_map_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(400, 50))
        self.frame_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_7.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_7.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_7.addWidget(self.pushButton_4)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        ClearMapGui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ClearMapGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1950, 22))
        self.menubar.setObjectName("menubar")
        self.file_menu = QtWidgets.QMenu(self.menubar)
        self.file_menu.setObjectName("file_menu")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        ClearMapGui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ClearMapGui)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        ClearMapGui.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(ClearMapGui)
        self.dockWidget.setMinimumSize(QtCore.QSize(108, 127))
        self.dockWidget.setBaseSize(QtCore.QSize(0, 127))
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.dockWidgetContents)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_4.addWidget(self.textBrowser)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.dockWidget.setWidget(self.dockWidgetContents)
        ClearMapGui.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget)
        self.graphDock = QtWidgets.QDockWidget(ClearMapGui)
        self.graphDock.setMinimumSize(QtCore.QSize(1529, 900))
        self.graphDock.setBaseSize(QtCore.QSize(0, 1748))
        self.graphDock.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.graphDock.setObjectName("graphDock")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setMinimumSize(QtCore.QSize(1529, 0))
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.graphLayout = QtWidgets.QGridLayout()
        self.graphLayout.setObjectName("graphLayout")
        self.frame = QtWidgets.QFrame(self.dockWidgetContents_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.graphLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.horizontalLayout_6.addLayout(self.graphLayout)
        self.graphDock.setWidget(self.dockWidgetContents_2)
        ClearMapGui.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.graphDock)
        self.actionPreferences = QtWidgets.QAction(ClearMapGui)
        self.actionPreferences.setObjectName("actionPreferences")
        self.menuEdit.addAction(self.actionPreferences)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(ClearMapGui)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ClearMapGui)

    def retranslateUi(self, ClearMapGui):
        _translate = QtCore.QCoreApplication.translate
        ClearMapGui.setWindowTitle(_translate("ClearMapGui", "ClearMapGui"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sample_tab), _translate("ClearMapGui", "Sample info"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.preprocessing_tab), _translate("ClearMapGui", "Preprocessing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cell_map_tab), _translate("ClearMapGui", "CellMap"))
        self.pushButton_6.setText(_translate("ClearMapGui", "< Previous"))
        self.pushButton_5.setText(_translate("ClearMapGui", "Preview"))
        self.pushButton_4.setText(_translate("ClearMapGui", "Next >"))
        self.file_menu.setTitle(_translate("ClearMapGui", "File"))
        self.menuEdit.setTitle(_translate("ClearMapGui", "Edit"))
        self.dockWidget.setWindowTitle(_translate("ClearMapGui", "Log"))
        self.graphDock.setWindowTitle(_translate("ClearMapGui", "Data viewer"))
        self.actionPreferences.setText(_translate("ClearMapGui", "Preferences"))
