clearmap_schema: 3
clearmap_version: "3.1.0"

templates:
  channel:
    detection:
      colocalization_compatible: false
      background_correction:
        diameter: [10, 10]
      maxima_detection:
        shape: 5
        h_max: null
      shape_detection:
        threshold: 500
      test_set_slicing:
        dim_0: [0, 200]
        dim_1: [0, 300]
        dim_2: [0, 400]
    cell_filtration:
      thresholds:
        size: [50, 900]
        intensity: null
    voxelization:
      radii: [5, 5, 5]
    run:
      plot_when_finished: false

performance:
  templates:
    channel:
      detection:
        block_processing:
          n_processes: 10
          size_min: 10
          size_max: 16
          overlap: 5
