clearmap_schema: 3
clearmap_version: "3.1.0"

templates:
  channel:
    comparison:
      particle_diameter: 30
    analysis:
      max_particle_distance: 10
      relative_overlap_threshold: 0.5
      voxel_number_overlap_threshold: 0
    voxelization:
      radii: [5, 5, 5]
    performance:
      n_processes: -1    # -1: all but one; None: all
