clearmap_schema: 3
clearmap_version: "3.1.0"

verbosity: "trace"
start_folder: "~/"
temp_folder: null
start_full_screen: false
default_lut: "white"
three_d_plot_bg: "grey"
font_size: 8
pattern_finder_min_n_files: 10
elastix_path: null
